### ISSUE TITLE
Sprites with Z-index > 0 makes scenes render above other windows.

### ISSUE THREAD

**Issue by MatheusPese** [MightyPrinny/godot-scene-palette#3]
Exemple:
![image](https://user-images.githubusercontent.com/7685880/81059165-50d3e200-8ea6-11ea-8f23-3df6323bd845.png)

**Comment by MightyPrinny** [comment]
Both of your issues should be fixed in master, but I'll leave them open for now until you confirm the problems have been fixed.

**Comment by MatheusPese** [comment]
> Both of your issues should be fixed in master, but I'll leave them open for now until you confirm the problems have been fixed.

Thanks, it is working perfectly now!
